services:
  ai-assistant:
    networks:
      - ai-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_AI_GOOGLE_GENAI_API-KEY=${GEMINI_API_KEY}
    image: mad:0.0.1-SNAPSHOT
    container_name: ai-assistant

networks:
  ai-network:
    driver: bridge